export const CURRENT_WEEK = '2026-06-22'

export const initialMeals = [
  { id: "w-b",  week_key: "2026-06-22", day: "Wednesday", date: "Jun 24", meal_type: "breakfast", emoji: "☀️", name: "Fend for Yourself", description: "Everyone's on their own.", store: null, store_type: null, cook: null, status: "set", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "w-l",  week_key: "2026-06-22", day: "Wednesday", date: "Jun 24", meal_type: "lunch",     emoji: "🥙", name: "Leftovers / Fend for Yourself", description: "Check the fridge.", store: null, store_type: null, cook: null, status: "set", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "w-d",  week_key: "2026-06-22", day: "Wednesday", date: "Jun 24", meal_type: "dinner",    emoji: "🥗", name: "Caesar Salad", description: "Romaine, shaved parm, croutons, Caesar + splash of Italian, grilled skillet chicken tenderloins", store: "Aldi", store_type: "instacart", cook: "Kayla 👩‍🍳", status: "confirmed", ian: "agree", ian_note: "", kayla: "agree", kayla_note: "", cook_note: "Perfect first cook! Recipe locked June 24, 2026. 35 min total, made 2 beautiful plates.", recipe_id: "caesar-salad" },
  { id: "th-b", week_key: "2026-06-22", day: "Thursday",  date: "Jun 25", meal_type: "breakfast", emoji: "☀️", name: "Fend for Yourself", description: "Everyone's on their own.", store: null, store_type: null, cook: null, status: "set", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "th-l", week_key: "2026-06-22", day: "Thursday",  date: "Jun 25", meal_type: "lunch",     emoji: "🥙", name: "Leftovers / Fend for Yourself", description: "Caesar salad leftovers or on your own.", store: null, store_type: null, cook: null, status: "set", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "th-d", week_key: "2026-06-22", day: "Thursday",  date: "Jun 25", meal_type: "dinner",    emoji: "🍔", name: "Smash Burgers", description: "Cattlemen's Ranch smash patties, Pepperidge Farm butter buns, bacon — toppings TBD after first cook", store: "Instacart", store_type: "instacart", cook: null, status: "draft", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "f-b",  week_key: "2026-06-22", day: "Friday",    date: "Jun 26", meal_type: "breakfast", emoji: "☀️", name: "Fend for Yourself", description: "Everyone's on their own.", store: null, store_type: null, cook: null, status: "set", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "f-l",  week_key: "2026-06-22", day: "Friday",    date: "Jun 26", meal_type: "lunch",     emoji: "🥙", name: "Leftovers / Fend for Yourself", description: "Burger leftovers or on your own.", store: null, store_type: null, cook: null, status: "set", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: null },
  { id: "f-d",  week_key: "2026-06-22", day: "Friday",    date: "Jun 26", meal_type: "dinner",    emoji: "🍝", name: "Spaghetti", description: "Hot & mild Italian sausage, Bertolli sauce (3 jars), Reggano spaghetti, peppers & onions. Big batch!", store: "Instacart", store_type: "instacart", cook: "Kayla 👩‍🍳", status: "cooked", ian: null, ian_note: "", kayla: null, kayla_note: "", cook_note: "", recipe_id: "spaghetti" },
]

export const initialRecipes = [
  {
    id: "caesar-salad",
    name: "🥗 Caesar Salad",
    status: "confirmed",
    confirmed_date: "June 24, 2026",
    description: "Kayla's version — whole romaine leaves, shaved parm, croutons, skillet chicken",
    prep_time: "~10 min",
    cook_time: "35 min",
    photo: null,
    dishes: ["Large salad bowl","Skillet","Cutting board & knife","Tongs","Potato peeler (for parmesan)","2 dinner plates"],
    freezer_items: [{ id: "f1", label: "Chicken Tenderloins", thawed: false }],
    ingredients: [
      { name: "Kirkwood Chicken Tenderloins — 5 tenderloins per batch", price: 7.98 },
      { name: "Romaine — 1.5 heads, ends cut, leaves kept whole", price: 4.09 },
      { name: "Caesar Dressing (brand of choice) — ¼ cup", price: 3.65 },
      { name: "Italian Dressing (brand of choice) — 1 tbsp", price: 2.15 },
      { name: "Croutons (brand of choice)", price: 1.29 },
      { name: "Parmesan Wedge — shaved with potato peeler", price: 4.85 },
      { name: "½ tbsp Dijon mustard — rubbed on chicken", price: null },
      { name: "½ tsp garlic powder", price: null },
      { name: "½ tsp onion powder", price: null },
      { name: "½ tsp paprika", price: null },
      { name: "¼ tsp ground mustard", price: null },
      { name: "½ tsp Grill Mates Roasted Garlic & Herb", price: null },
      { name: "Salt & pepper to taste", price: null },
      { name: "Fresh cracked pepper — to finish", price: null },
      { name: "Oil — to coat the pan", price: null },
    ],
    steps: [
      { step: 1, title: "Season the Chicken", detail: "Rub ½ tbsp Dijon mustard directly onto the chicken tenderloins first. Then season with ½ tsp garlic powder, ½ tsp onion powder, ½ tsp paprika, ¼ tsp ground mustard, ½ tsp Grill Mates Roasted Garlic & Herb, salt and pepper." },
      { step: 2, title: "Heat the Skillet", detail: "Place skillet on stove over medium-high heat. Add a light coat of oil and let it get fully hot before adding the chicken." },
      { step: 3, title: "Cook the Chicken", detail: "Add tenderloins to the hot skillet. Cook until fully done with a good sear — no pink inside. Do not rush." },
      { step: 4, title: "Prep the Romaine", detail: "Use 1.5 heads of romaine. Cut the ends off but keep the leaves whole — do not chop. They will be laid out flat on the plate." },
      { step: 5, title: "Mix the Dressing", detail: "In the large salad bowl, combine ¼ cup Caesar dressing and 1 tbsp Italian dressing. Mix together in the bowl first before adding any lettuce." },
      { step: 6, title: "Toss the Lettuce", detail: "Add the whole romaine leaves to the bowl and toss to coat. Leaves stay whole." },
      { step: 7, title: "Add Croutons", detail: "Toss croutons into the dressed romaine so they get lightly coated." },
      { step: 8, title: "Plate the Salad", detail: "Lay the dressed whole romaine leaves out flat side by side on the plate — not piled, laid out next to each other." },
      { step: 9, title: "Shave the Parmesan", detail: "Use a potato peeler to shave thin slices of parmesan directly over the plated salad." },
      { step: 10, title: "Add Chicken & Finish", detail: "Slice or chop the chicken and add on top immediately while still hot. Finish with fresh cracked pepper to preference. Serve right away." },
    ],
    notes: "🔒 Confirmed June 24, 2026. Makes 2 plates. Key: Dijon on chicken first, dressing mixed in bowl before lettuce, romaine whole and laid flat, potato peeler for parmesan. Serve immediately.",
    store: "Aldi / Instacart",
  },
  {
    id: "spaghetti",
    name: "🍝 Spaghetti",
    status: "draft",
    confirmed_date: null,
    description: "Kayla's version — layered seasoning, hot & mild Italian sausage, Bertolli sauce, peppers & onions",
    prep_time: "~15 min",
    cook_time: "65 min",
    photo: null,
    dishes: ["Large pot (sauce)","Separate pot (noodles)","Cutting board & knife","Wooden spoon or spatula"],
    freezer_items: [{ id: "f1", label: "Hot Italian Sausage", thawed: false }, { id: "f2", label: "Mild Italian Sausage", thawed: false }],
    ingredients: [
      { name: "Johnsonville Hot Italian Ground Sausage — 16 oz", price: 4.89 },
      { name: "Johnsonville Mild Italian Ground Sausage — 16 oz", price: 4.89 },
      { name: "Bertolli Pasta Sauce — 3 jars", price: 15.27 },
      { name: "Reggano Spaghetti Noodles", price: 2.09 },
      { name: "1 whole onion — diced", price: null },
      { name: "1 red bell pepper — sliced", price: null },
      { name: "1 yellow bell pepper — sliced", price: null },
      { name: "Half a bulb of garlic — roughly chopped", price: null },
      { name: "Oil — for the pot, add more as needed", price: null },
      { name: "Butter — about ⅓ of a stick", price: null },
      { name: "Paprika — 1 tsp (veggies) + 2 tsp (meat) + more for sauce", price: null },
      { name: "Italian seasoning — ½ tsp + 2 tsp + more for sauce", price: null },
      { name: "Granulated onion — ½ tsp + 2 tsp + more for sauce", price: null },
      { name: "Granulated garlic — ½ tsp + 2 tsp + more for sauce", price: null },
      { name: "Thyme — ½ tsp + 2 tsp + more for sauce", price: null },
      { name: "Cayenne pepper — pinch at veggie stage", price: null },
      { name: "Salt & pepper — splash at each stage", price: null },
    ],
    steps: [
      { step: 1, title: "Prep the Veggies", detail: "Dice the whole onion. Slice the red and yellow bell peppers. Roughly chop half a bulb of garlic and set aside — garlic goes in after veggies sweat." },
      { step: 2, title: "Start the Pot", detail: "Heat a large pot over medium heat. Add a little oil and about ⅓ stick of butter." },
      { step: 3, title: "Cook the Veggies", detail: "Add onion and peppers. Season with 1 tsp paprika, ½ tsp each Italian seasoning, granulated onion, granulated garlic, thyme, pinch of cayenne, splash of salt and pepper. Cook until soft." },
      { step: 4, title: "Add the Garlic", detail: "Once veggies are soft add the chopped garlic. Cook until fragrant — about 1 to 2 minutes. Do not burn." },
      { step: 5, title: "Add the Sausage", detail: "Add both 16 oz hot and mild Italian ground sausage. Add more oil if needed. Break up and chop meat as it cooks." },
      { step: 6, title: "Season the Meat", detail: "Once broken up, season again heavier: 2 tsp each paprika, Italian seasoning, granulated onion, granulated garlic, thyme, plus salt and pepper. Stir well." },
      { step: 7, title: "Finish Chopping the Meat", detail: "Let cook a minute or two, chop again until fully broken down. Cook until mostly done — no large pink pieces." },
      { step: 8, title: "Add the Sauce", detail: "Pour in all 3 jars of Bertolli pasta sauce. Stir to combine." },
      { step: 9, title: "Season the Sauce", detail: "Season again with same spices to taste. Simmer on low, stirring occasionally, until everything comes together." },
      { step: 10, title: "Cook the Noodles", detail: "Boil separate pot of salted water. Cook Reggano spaghetti per package directions until al dente. Drain well." },
      { step: 11, title: "Serve", detail: "Preferred: plate noodles first and top with sauce. Can also combine in pot. Either works." },
    ],
    notes: "Draft — confirm after eating. Makes a large batch. Key technique: season in layers at every stage — veggies, meat, and sauce each get their own round. The layering builds the flavor.",
    store: "Instacart",
  },
]
