export const CURRENT_WEEK = '2026-06-22'
export const NEXT_WEEK = '2026-06-29'

export const initialMeals = [
  // ── CURRENT WEEK (Jun 24–26) ──────────────────────────────────────────────
  { id:"w-b",  week_key:"2026-06-22", day:"Wednesday", date:"Jun 24", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"w-l",  week_key:"2026-06-22", day:"Wednesday", date:"Jun 24", meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Check the fridge.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"w-d",  week_key:"2026-06-22", day:"Wednesday", date:"Jun 24", meal_type:"dinner",    emoji:"🥗", name:"Caesar Salad", description:"Romaine, shaved parm, croutons, Caesar + splash of Italian, grilled skillet chicken tenderloins", store:"Aldi", store_type:"instacart", cook:"Kayla 👩🏾‍🍳", status:"confirmed", ian:"agree", ian_note:"", kayla:"agree", kayla_note:"", cook_note:"Perfect first cook! Recipe locked June 24, 2026. 35 min total, made 2 beautiful plates.", recipe_id:"caesar-salad" },
  { id:"th-b", week_key:"2026-06-22", day:"Thursday",  date:"Jun 25", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"th-l", week_key:"2026-06-22", day:"Thursday",  date:"Jun 25", meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Caesar salad leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"th-d", week_key:"2026-06-22", day:"Thursday",  date:"Jun 25", meal_type:"dinner",    emoji:"🍔", name:"Smash Burgers", description:"Cattlemen's Ranch smash patties, Pepperidge Farm butter buns, bacon — toppings TBD after first cook", store:"Instacart", store_type:"instacart", cook:null, status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"f-b",  week_key:"2026-06-22", day:"Friday",    date:"Jun 26", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"f-l",  week_key:"2026-06-22", day:"Friday",    date:"Jun 26", meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Burger leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"f-d",  week_key:"2026-06-22", day:"Friday",    date:"Jun 26", meal_type:"dinner",    emoji:"🍝", name:"Spaghetti", description:"Hot & mild Italian sausage, Bertolli sauce (3 jars), Reggano spaghetti, peppers & onions. Big batch!", store:"Instacart", store_type:"instacart", cook:"Kayla 👩🏾‍🍳", status:"cooked", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"spaghetti" },

  // ── SATURDAY Jun 27 (still current week) ─────────────────────────────────
  { id:"sa-b", week_key:"2026-06-22", day:"Saturday",  date:"Jun 27", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"sa-l", week_key:"2026-06-22", day:"Saturday",  date:"Jun 27", meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Spaghetti leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"sa-d", week_key:"2026-06-22", day:"Saturday",  date:"Jun 27", meal_type:"dinner",    emoji:"🍽️", name:"Leftovers", description:"Finishing off whatever is left from this week.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },

  // ── SUNDAY Jun 28 (still current week) ───────────────────────────────────
  { id:"su-b", week_key:"2026-06-22", day:"Sunday",    date:"Jun 28", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"su-l", week_key:"2026-06-22", day:"Sunday",    date:"Jun 28", meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Fridge check before the new week.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"su-d", week_key:"2026-06-22", day:"Sunday",    date:"Jun 28", meal_type:"dinner",    emoji:"🐟", name:"Pan Seared Branzino", description:"Fresh whole branzino or sea bass from Harford Seafood, sautéed broccolini, garlic butter mashed yellow potatoes", store:"Harford Seafood", store_type:"inperson", cook:"Kayla 👩🏾‍🍳", status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"pan-seared-fish" },

  // ── NEXT WEEK (Jun 29 – Jul 5) ────────────────────────────────────────────
  { id:"nw-mon-b", week_key:"2026-06-29", day:"Monday",    date:"Jun 29", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-mon-l", week_key:"2026-06-29", day:"Monday",    date:"Jun 29", meal_type:"lunch",     emoji:"🥙", name:"Spaghetti Leftovers", description:"Leftover spaghetti from last week.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-mon-d", week_key:"2026-06-29", day:"Monday",    date:"Jun 29", meal_type:"dinner",    emoji:"🍔", name:"Smash Burgers", description:"Cattlemen's Ranch smash patties, Pepperidge Farm butter buns, bacon, granulated garlic & onion, Season All", store:"Aldi", store_type:"instacart", cook:null, status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"smash-burgers" },
  { id:"nw-tue-b", week_key:"2026-06-29", day:"Tuesday",   date:"Jun 30", meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-tue-l", week_key:"2026-06-29", day:"Tuesday",   date:"Jun 30", meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Burger leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-tue-d", week_key:"2026-06-29", day:"Tuesday",   date:"Jun 30", meal_type:"dinner",    emoji:"🍗", name:"Oven Baked Wings & Gravy", description:"Seasoned oven baked wings, gravy from packet with remix, served over plain rice with sautéed spinach", store:"Aldi", store_type:"instacart", cook:"Kayla 👩🏾‍🍳", status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"wings-gravy-rice" },
  { id:"nw-wed-b", week_key:"2026-06-29", day:"Wednesday",  date:"Jul 1",  meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-wed-l", week_key:"2026-06-29", day:"Wednesday",  date:"Jul 1",  meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Wing leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-wed-d", week_key:"2026-06-29", day:"Wednesday",  date:"Jul 1",  meal_type:"dinner",    emoji:"🍗", name:"Deep Fried Chicken Tenders & Waffle Fries", description:"Buttermilk battered deep fried chicken tenders Popeyes-style, waffle fries from freezer", store:"Aldi", store_type:"instacart", cook:"Kayla 👩🏾‍🍳", status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"fried-tenders" },
  { id:"nw-thu-b", week_key:"2026-06-29", day:"Thursday",   date:"Jul 2",  meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-thu-l", week_key:"2026-06-29", day:"Thursday",   date:"Jul 2",  meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Tender leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-thu-d", week_key:"2026-06-29", day:"Thursday",   date:"Jul 2",  meal_type:"dinner",    emoji:"🥗", name:"Grilled Chicken Caesar", description:"Our confirmed Caesar salad recipe — romaine, shaved parm, croutons, grilled skillet chicken tenderloins", store:"Aldi", store_type:"instacart", cook:"Kayla 👩🏾‍🍳", status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"caesar-salad" },
  { id:"nw-fri-b", week_key:"2026-06-29", day:"Friday",     date:"Jul 3",  meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-fri-l", week_key:"2026-06-29", day:"Friday",     date:"Jul 3",  meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Caesar leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-fri-d", week_key:"2026-06-29", day:"Friday",     date:"Jul 3",  meal_type:"dinner",    emoji:"🐟", name:"Fried Fish & Homemade Mac and Cheese", description:"Fried fish (fresh from Harford Seafood or from freezer depending on Sunday leftovers), homemade sharp cheddar baked mac and cheese, steamed broccoli", store:"Harford Seafood", store_type:"inperson", cook:"Kayla 👩🏾‍🍳", status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"fried-fish-mac" },
  { id:"nw-sat-b", week_key:"2026-06-29", day:"Saturday",   date:"Jul 4",  meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-sat-l", week_key:"2026-06-29", day:"Saturday",   date:"Jul 4",  meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Fish or mac leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-sat-d", week_key:"2026-06-29", day:"Saturday",   date:"Jul 4",  meal_type:"dinner",    emoji:"🍕", name:"Homemade Pizza", description:"Aldi/Giant premade crust, Aldi pizza sauce, fresh mozzarella, pepperoni, Italian sausage, green pepper, spinach", store:"Aldi", store_type:"instacart", cook:"Kayla 👩🏾‍🍳", status:"draft", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:"homemade-pizza" },
  { id:"nw-sun-b", week_key:"2026-06-29", day:"Sunday",     date:"Jul 5",  meal_type:"breakfast", emoji:"☀️", name:"Fend for Yourself", description:"Everyone's on their own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-sun-l", week_key:"2026-06-29", day:"Sunday",     date:"Jul 5",  meal_type:"lunch",     emoji:"🥙", name:"Leftovers / Fend for Yourself", description:"Pizza leftovers or on your own.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
  { id:"nw-sun-d", week_key:"2026-06-29", day:"Sunday",     date:"Jul 5",  meal_type:"dinner",    emoji:"🍽️", name:"Leftovers", description:"Finishing off whatever is left from the week.", store:null, store_type:null, cook:null, status:"set", ian:null, ian_note:"", kayla:null, kayla_note:"", cook_note:"", recipe_id:null },
]

export const initialRecipes = [
  // ── CAESAR SALAD (confirmed) ──────────────────────────────────────────────
  {
    id: "caesar-salad",
    name: "🥗 Caesar Salad",
    status: "confirmed",
    confirmed_date: "June 24, 2026",
    description: "Kayla's version — whole romaine leaves, shaved parm, croutons, skillet chicken",
    prep_time: "~10 min",
    cook_time: "35 min",
    dishes: ["Large salad bowl","Skillet","Cutting board & knife","Tongs","Potato peeler (for parmesan)","2 dinner plates"],
    freezer_items: [{ id:"f1", label:"Chicken Tenderloins", thawed:false }],
    ingredients: [
      { name:"Kirkwood Chicken Tenderloins — 5 tenderloins per batch", price:7.98 },
      { name:"Romaine — 1.5 heads, ends cut, leaves kept whole", price:4.09 },
      { name:"Caesar Dressing (brand of choice) — ¼ cup", price:3.65 },
      { name:"Italian Dressing (brand of choice) — 1 tbsp", price:2.15 },
      { name:"Croutons (brand of choice)", price:1.29 },
      { name:"Parmesan Wedge — shaved with potato peeler", price:4.85 },
      { name:"½ tbsp Dijon mustard — rubbed on chicken", price:null },
      { name:"½ tsp garlic powder", price:null },
      { name:"½ tsp onion powder", price:null },
      { name:"½ tsp paprika", price:null },
      { name:"¼ tsp ground mustard", price:null },
      { name:"½ tsp Grill Mates Roasted Garlic & Herb", price:null },
      { name:"Salt & pepper to taste", price:null },
      { name:"Fresh cracked pepper — to finish", price:null },
      { name:"Oil — to coat the pan", price:null },
    ],
    steps: [
      { step:1, title:"Season the Chicken", detail:"Rub ½ tbsp Dijon mustard directly onto the chicken tenderloins first. Then season with ½ tsp garlic powder, ½ tsp onion powder, ½ tsp paprika, ¼ tsp ground mustard, ½ tsp Grill Mates Roasted Garlic & Herb, salt and pepper." },
      { step:2, title:"Heat the Skillet", detail:"Place skillet on stove over medium-high heat. Add a light coat of oil and let it get fully hot before adding the chicken." },
      { step:3, title:"Cook the Chicken", detail:"Add tenderloins to the hot skillet. Cook until fully done with a good sear — no pink inside. Do not rush." },
      { step:4, title:"Prep the Romaine", detail:"Use 1.5 heads of romaine. Cut the ends off but keep the leaves whole — do not chop. They will be laid out flat on the plate." },
      { step:5, title:"Mix the Dressing", detail:"In the large salad bowl, combine ¼ cup Caesar dressing and 1 tbsp Italian dressing. Mix together in the bowl first before adding any lettuce." },
      { step:6, title:"Toss the Lettuce", detail:"Add the whole romaine leaves to the bowl and toss to coat. Leaves stay whole." },
      { step:7, title:"Add Croutons", detail:"Toss croutons into the dressed romaine so they get lightly coated." },
      { step:8, title:"Plate the Salad", detail:"Lay the dressed whole romaine leaves out flat side by side on the plate — not piled, laid out next to each other." },
      { step:9, title:"Shave the Parmesan", detail:"Use a potato peeler to shave thin slices of parmesan directly over the plated salad." },
      { step:10, title:"Add Chicken & Finish", detail:"Slice or chop the chicken and add on top immediately while still hot. Finish with fresh cracked pepper to preference. Serve right away." },
    ],
    notes: "🔒 Confirmed June 24, 2026. Makes 2 plates. Key: Dijon on chicken first, dressing mixed in bowl before lettuce, romaine whole and laid flat, potato peeler for parmesan. Serve immediately.",
    store: "Aldi / Instacart",
  },

  // ── SPAGHETTI (draft) ─────────────────────────────────────────────────────
  {
    id: "spaghetti",
    name: "🍝 Spaghetti",
    status: "draft",
    confirmed_date: null,
    description: "Kayla's version — layered seasoning, hot & mild Italian sausage, Bertolli sauce, peppers & onions",
    prep_time: "~15 min",
    cook_time: "65 min",
    dishes: ["Large pot (sauce)","Separate pot (noodles)","Cutting board & knife","Wooden spoon or spatula"],
    freezer_items: [
      { id:"f1", label:"Hot Italian Sausage", thawed:false },
      { id:"f2", label:"Mild Italian Sausage", thawed:false },
    ],
    ingredients: [
      { name:"Johnsonville Hot Italian Ground Sausage — 16 oz", price:4.89 },
      { name:"Johnsonville Mild Italian Ground Sausage — 16 oz", price:4.89 },
      { name:"Bertolli Pasta Sauce — 3 jars", price:15.27 },
      { name:"Reggano Spaghetti Noodles", price:2.09 },
      { name:"1 whole onion — diced", price:null },
      { name:"1 red bell pepper — sliced", price:null },
      { name:"1 yellow bell pepper — sliced", price:null },
      { name:"Half a bulb of garlic — roughly chopped", price:null },
      { name:"Oil — for the pot, add more as needed", price:null },
      { name:"Butter — about ⅓ of a stick", price:null },
      { name:"Paprika — 1 tsp (veggies) + 2 tsp (meat) + more for sauce", price:null },
      { name:"Italian seasoning — ½ tsp + 2 tsp + more for sauce", price:null },
      { name:"Granulated onion — ½ tsp + 2 tsp + more for sauce", price:null },
      { name:"Granulated garlic — ½ tsp + 2 tsp + more for sauce", price:null },
      { name:"Thyme — ½ tsp + 2 tsp + more for sauce", price:null },
      { name:"Cayenne pepper — pinch at veggie stage", price:null },
      { name:"Salt & pepper — splash at each stage", price:null },
    ],
    steps: [
      { step:1, title:"Prep the Veggies", detail:"Dice the whole onion. Slice the red and yellow bell peppers. Roughly chop half a bulb of garlic and set aside — garlic goes in after veggies sweat." },
      { step:2, title:"Start the Pot", detail:"Heat a large pot over medium heat. Add a little oil and about ⅓ stick of butter." },
      { step:3, title:"Cook the Veggies", detail:"Add onion and peppers. Season with 1 tsp paprika, ½ tsp each Italian seasoning, granulated onion, granulated garlic, thyme, pinch of cayenne, splash of salt and pepper. Cook until soft." },
      { step:4, title:"Add the Garlic", detail:"Once veggies are soft add the chopped garlic. Cook until fragrant — about 1 to 2 minutes. Do not burn." },
      { step:5, title:"Add the Sausage", detail:"Add both 16 oz hot and mild Italian ground sausage. Add more oil if needed. Break up and chop meat as it cooks." },
      { step:6, title:"Season the Meat", detail:"Once broken up, season again heavier: 2 tsp each paprika, Italian seasoning, granulated onion, granulated garlic, thyme, plus salt and pepper. Stir well." },
      { step:7, title:"Finish Chopping the Meat", detail:"Let cook a minute or two, chop again until fully broken down. Cook until mostly done — no large pink pieces." },
      { step:8, title:"Add the Sauce", detail:"Pour in all 3 jars of Bertolli pasta sauce. Stir to combine." },
      { step:9, title:"Season the Sauce", detail:"Season again with same spices to taste. Simmer on low, stirring occasionally, until everything comes together." },
      { step:10, title:"Cook the Noodles", detail:"Boil separate pot of salted water. Cook Reggano spaghetti per package directions until al dente. Drain well." },
      { step:11, title:"Serve", detail:"Preferred: plate noodles first and top with sauce. Can also combine in pot. Either works." },
    ],
    notes: "Draft — confirm after eating. Makes a large batch. Key technique: season in layers at every stage — veggies, meat, and sauce each get their own round. The layering builds the flavor.",
    store: "Instacart",
  },

  // ── PAN SEARED FISH (draft) ───────────────────────────────────────────────
  {
    id: "pan-seared-fish",
    name: "🐟 Pan Seared Branzino",
    status: "draft",
    confirmed_date: null,
    description: "Fresh whole branzino or sea bass, sautéed broccolini, garlic butter mashed yellow potatoes",
    prep_time: "~20 min",
    cook_time: "TBC",
    dishes: ["Large skillet or cast iron","Pot for mashing","Cutting board & knife","Tongs","Sauté pan (broccolini)"],
    freezer_items: [{ id:"f1", label:"Fish (if not using fresh)", thawed:false }],
    ingredients: [
      { name:"Branzino or Sea Bass — whole or fillet (Harford Seafood)", price:null },
      { name:"Yellow potatoes", price:null },
      { name:"Butter — for mash and searing", price:null },
      { name:"Whole milk — for mash", price:null },
      { name:"Sour cream — for mash", price:null },
      { name:"Chives — for mash topping", price:null },
      { name:"Broccolini", price:null },
      { name:"Garlic — for broccolini sauté", price:null },
      { name:"Oil — for pan searing fish", price:null },
      { name:"Salt & pepper — for fish, mash, and broccolini", price:null },
      { name:"Seasonings for fish — TBC after first cook", price:null },
    ],
    steps: [
      { step:1, title:"Prep & Season the Fish", detail:"Clean and pat the branzino dry. Season inside and out with salt, pepper, and seasonings of choice (TBC after first cook). Score the skin if using whole fish." },
      { step:2, title:"Boil the Potatoes", detail:"Cut yellow potatoes into chunks. Boil in salted water until fork tender — about 15 to 20 minutes." },
      { step:3, title:"Make the Mash", detail:"Drain potatoes. Mash with butter, warm milk, sour cream, salt and pepper to taste. Top with chives before serving." },
      { step:4, title:"Sauté the Broccolini", detail:"Heat oil and a little butter in a pan over medium-high heat. Add garlic and cook until fragrant. Add broccolini, season with salt and pepper, sauté until tender with a slight char — about 5 to 7 minutes." },
      { step:5, title:"Sear the Fish", detail:"Heat a skillet or cast iron over high heat with oil. Place fish skin-side down. Press gently. Sear without moving until skin is crispy — about 3 to 4 minutes per side depending on thickness. Do not overcrowd the pan." },
      { step:6, title:"Plate & Serve", detail:"Plate mash, broccolini, and fish together. Serve immediately." },
    ],
    notes: "Draft — confirm fish type, seasoning, and cook time after first cook. Fish comes fresh from Harford Seafood (in person). If using frozen in the future, thaw fully before cooking. Freezer button available for that purpose.",
    store: "Harford Seafood (in person)",
  },

  // ── SMASH BURGERS (draft) ─────────────────────────────────────────────────
  {
    id: "smash-burgers",
    name: "🍔 Smash Burgers",
    status: "draft",
    confirmed_date: null,
    description: "Cattlemen's Ranch Aldi smash patties — brand approved. Seasoning TBC once Season All is restocked.",
    prep_time: "~10 min",
    cook_time: "TBC",
    dishes: ["Skillet or griddle","Spatula","Cutting board","Plates"],
    freezer_items: [{ id:"f1", label:"Cattlemen's Ranch Smash Patties", thawed:false }],
    ingredients: [
      { name:"Cattlemen's Ranch Smash Burger Patties (Aldi)", price:10.99 },
      { name:"Pepperidge Farm Farmhouse Butter Buns", price:5.89 },
      { name:"Appleton Farms Center Cut Bacon", price:5.19 },
      { name:"Granulated garlic — to season patties", price:null },
      { name:"Granulated onion — to season patties", price:null },
      { name:"Season All — to season patties (restock needed)", price:null },
      { name:"Sliced cheese — of choice", price:null },
      { name:"Toppings — TBC after first confirmed cook", price:null },
    ],
    steps: [
      { step:1, title:"Season the Patties", detail:"Season raw patties with granulated garlic, granulated onion, and Season All (once restocked). Season both sides generously." },
      { step:2, title:"Heat the Skillet", detail:"Heat skillet or griddle over high heat until very hot. This is key for a proper smash burger crust." },
      { step:3, title:"Smash & Cook", detail:"Place patty on hot surface and immediately press down firmly with spatula to smash thin. Cook 2 to 3 minutes without moving. Flip and add cheese if desired. Cook 1 to 2 more minutes." },
      { step:4, title:"Cook the Bacon", detail:"Cook bacon in the same pan or separately to desired crispness." },
      { step:5, title:"Build & Serve", detail:"Assemble on butter buns with bacon and toppings of choice. Serve immediately." },
    ],
    notes: "Draft — Cattlemen's Ranch from Aldi is approved brand. Season All was out of stock on first cook — full seasoning TBC once restocked. Toppings to be confirmed after first proper cook.",
    store: "Aldi / Instacart",
  },

  // ── WINGS & GRAVY (draft) ─────────────────────────────────────────────────
  {
    id: "wings-gravy-rice",
    name: "🍗 Oven Baked Wings & Gravy",
    status: "draft",
    confirmed_date: null,
    description: "Seasoned oven baked wings, packet gravy with remix, plain rice, sautéed spinach with Knorr chicken bouillon",
    prep_time: "~15 min",
    cook_time: "TBC",
    dishes: ["Baking sheet","Pot for rice","Pot for gravy","Sauté pan for spinach","Mixing bowl"],
    freezer_items: [{ id:"f1", label:"Chicken Wings (16)", thawed:false }],
    ingredients: [
      { name:"Chicken wings — 16 from freezer", price:null },
      { name:"Seasonings for wings — TBC after first cook", price:null },
      { name:"Gravy packet — base", price:null },
      { name:"Gravy remix ingredients — TBC after first cook", price:null },
      { name:"Grain rice — plain", price:null },
      { name:"Fresh spinach", price:null },
      { name:"Knorr Chicken Bouillon powder — for spinach sauté", price:null },
      { name:"Butter or oil — for spinach", price:null },
      { name:"Garlic — for spinach", price:null },
    ],
    steps: [
      { step:1, title:"Season & Prep Wings", detail:"Pat wings dry. Season with seasonings of choice (TBC after first cook). Let sit while oven preheats." },
      { step:2, title:"Bake the Wings", detail:"Preheat oven — temperature TBC. Arrange wings on baking sheet in single layer. Bake until cooked through and skin is crispy. Flip halfway. Cook time TBC after first cook." },
      { step:3, title:"Cook the Rice", detail:"Cook grain rice per package directions in salted water. Plain — the gravy will carry the flavor." },
      { step:4, title:"Make the Gravy", detail:"Start with gravy packet per instructions, then remix and build it up from there. Details TBC after first cook." },
      { step:5, title:"Sauté the Spinach", detail:"Heat butter or oil in a pan over medium heat. Add garlic, cook until fragrant. Add fresh spinach and a sprinkle of Knorr chicken bouillon powder. Sauté until wilted. Season to taste." },
      { step:6, title:"Plate & Serve", detail:"Serve wings and rice topped with gravy. Spinach on the side." },
    ],
    notes: "Draft — wing seasoning and gravy remix details TBC after first cook. Wings come from freezer — thaw night before. Spinach is seasoned with Knorr chicken bouillon which is the key flavoring.",
    store: "Aldi / Instacart",
  },

  // ── FRIED CHICKEN TENDERS (draft) ─────────────────────────────────────────
  {
    id: "fried-tenders",
    name: "🍗 Deep Fried Chicken Tenders",
    status: "draft",
    confirmed_date: null,
    description: "Buttermilk egg cornstarch flour battered deep fried tenders Popeyes-style, served with waffle fries from freezer",
    prep_time: "~20 min + marinate time",
    cook_time: "TBC",
    dishes: ["Large heavy pot for frying","Mixing bowls (2 — wet and dry)","Tongs","Wire rack or paper towels","Sheet pan for waffle fries"],
    freezer_items: [{ id:"f1", label:"Chicken Tenderloins", thawed:false }, { id:"f2", label:"Waffle Fries", thawed:false }],
    ingredients: [
      { name:"Chicken tenderloins — from freezer", price:null },
      { name:"Buttermilk — for marinade/wet dip", price:null },
      { name:"Eggs — for wet batter", price:null },
      { name:"Cornstarch — for coating", price:null },
      { name:"All-purpose flour — for coating", price:null },
      { name:"Seasonings for coating — TBC after first cook (Popeyes-style)", price:null },
      { name:"Oil — for deep frying (enough to submerge tenders)", price:null },
      { name:"Waffle fries — from freezer", price:null },
    ],
    steps: [
      { step:1, title:"Marinate the Chicken", detail:"Soak chicken tenderloins in buttermilk and egg mixture. Season the wet mixture. Let marinate — ideally at least 30 minutes, longer if possible." },
      { step:2, title:"Make the Dry Coating", detail:"Mix cornstarch, flour, and dry seasonings together in a bowl. Ratio and seasonings TBC after first cook for Popeyes-style result." },
      { step:3, title:"Heat the Oil", detail:"Fill a heavy pot with enough oil to fully submerge the tenders. Heat to frying temperature — around 350°F. Do not rush this step." },
      { step:4, title:"Coat the Tenders", detail:"Remove chicken from wet mixture, let excess drip off, then dredge thoroughly in the dry coating. Press coating firmly onto chicken." },
      { step:5, title:"Fry the Tenders", detail:"Carefully lower coated tenders into hot oil. Fry until golden brown and cooked through — no pink inside. Do not overcrowd the pot. Work in batches if needed. Cook time TBC." },
      { step:6, title:"Drain & Rest", detail:"Remove tenders and place on a wire rack or paper towels to drain. Season immediately with a little extra salt if desired." },
      { step:7, title:"Cook the Waffle Fries", detail:"Bake waffle fries from freezer per package directions while tenders rest." },
      { step:8, title:"Serve", detail:"Plate tenders and waffle fries together. Serve with dipping sauces of choice." },
    ],
    notes: "Draft — batter seasoning ratio TBC after first cook. Goal is Popeyes-style crispy coating. Tenderloins come from freezer — thaw night before. Fry on stovetop in heavy pot. Waffle fries from freezer stock.",
    store: "Aldi / Instacart",
  },

  // ── FRIED FISH & MAC (draft) ──────────────────────────────────────────────
  {
    id: "fried-fish-mac",
    name: "🐟 Fried Fish & Homemade Mac and Cheese",
    status: "draft",
    confirmed_date: null,
    description: "Fried fish (fresh from Harford Seafood or frozen), homemade sharp cheddar baked mac and cheese, steamed broccoli",
    prep_time: "~25 min",
    cook_time: "TBC",
    dishes: ["Heavy pot for frying","Large pot for mac","Baking dish (9x13)","Sauté pan for broccoli","Mixing bowls","Whisk"],
    freezer_items: [{ id:"f1", label:"Fish (if not using Sunday's fresh leftover)", thawed:false }],
    ingredients: [
      { name:"Fish — fresh from Harford Seafood or frozen if no Sunday leftovers", price:null },
      { name:"Fish coating — TBC after first cook", price:null },
      { name:"Oil — for frying fish", price:null },
      { name:"Elbow macaroni or pasta of choice", price:null },
      { name:"Sharp cheddar cheese — primary cheese", price:null },
      { name:"Additional cheeses — TBC at time of cooking", price:null },
      { name:"Butter — for cheese sauce roux", price:null },
      { name:"Flour — for roux", price:null },
      { name:"Whole milk — for cheese sauce", price:null },
      { name:"Salt, pepper, seasonings — for cheese sauce", price:null },
      { name:"Broccoli — steamed", price:null },
    ],
    steps: [
      { step:1, title:"Make the Cheese Sauce", detail:"Melt butter in a pot over medium heat. Whisk in flour to make a roux — cook 1 to 2 minutes. Slowly whisk in warm milk until smooth and thickened. Add sharp cheddar and other cheeses of choice. Stir until fully melted. Season to taste." },
      { step:2, title:"Cook the Pasta", detail:"Boil pasta in salted water until just under al dente — it will finish in the oven. Drain." },
      { step:3, title:"Combine & Bake", detail:"Mix cooked pasta into cheese sauce. Pour into greased baking dish. Bake at 350°F until bubbling and set on top — about 20 to 25 minutes. No toppings." },
      { step:4, title:"Prep the Fish", detail:"If using fresh — clean and pat dry. If using frozen — thaw fully first. Coat with seasoned batter (TBC after first cook)." },
      { step:5, title:"Fry the Fish", detail:"Heat oil in heavy pot to frying temperature. Fry fish until golden and cooked through. Drain on paper towels. Cook time TBC after first cook." },
      { step:6, title:"Steam the Broccoli", detail:"Steam broccoli until tender but not mushy. Season with salt, pepper, and butter if desired." },
      { step:7, title:"Plate & Serve", detail:"Serve fried fish alongside baked mac and cheese and broccoli." },
    ],
    notes: "Draft — fish comes from Harford Seafood fresh when possible. If leftover branzino from Sunday exists use that instead. Freezer button available for weeks when fish is frozen. Mac and cheese is cheese sauce baked — no toppings. Cheese blend TBC at time of cooking.",
    store: "Harford Seafood (in person) / Aldi",
  },

  // ── HOMEMADE PIZZA (draft) ────────────────────────────────────────────────
  {
    id: "homemade-pizza",
    name: "🍕 Homemade Pizza",
    status: "draft",
    confirmed_date: null,
    description: "Premade Aldi/Giant crust, Aldi pizza sauce, fresh mozzarella, pepperoni, Italian sausage, green pepper, spinach",
    prep_time: "~20 min",
    cook_time: "TBC",
    dishes: ["Pizza pan or baking sheet","Cutting board","Knife","Spoon for sauce"],
    freezer_items: [{ id:"f1", label:"Italian Sausage (if using from freezer)", thawed:false }],
    ingredients: [
      { name:"Premade pizza crust — Aldi or Giant", price:null },
      { name:"Aldi pizza sauce", price:null },
      { name:"Fresh mozzarella — sliced", price:null },
      { name:"Pepperoni", price:null },
      { name:"Italian sausage — ground or crumbled (Johnsonville or similar)", price:null },
      { name:"Green bell pepper — sliced", price:null },
      { name:"Fresh spinach", price:null },
      { name:"Olive oil or oil — to brush crust", price:null },
      { name:"Italian seasoning — to season", price:null },
    ],
    steps: [
      { step:1, title:"Preheat Oven", detail:"Preheat oven per pizza crust package instructions. Usually around 400 to 425°F." },
      { step:2, title:"Prep the Sausage", detail:"If using raw Italian sausage, brown and crumble it in a skillet first. Drain any excess grease. Set aside." },
      { step:3, title:"Build the Pizza", detail:"Lay out the premade crust. Brush edges lightly with oil. Spread pizza sauce evenly across the base — not too thick." },
      { step:4, title:"Add Toppings", detail:"Layer fresh mozzarella slices, pepperoni, cooked sausage, sliced green pepper, and fresh spinach. Season with Italian seasoning." },
      { step:5, title:"Bake", detail:"Bake per crust package directions until cheese is melted and bubbly and crust is golden. Time TBC after first cook." },
      { step:6, title:"Slice & Serve", detail:"Let rest 2 to 3 minutes before slicing. Serve hot." },
    ],
    notes: "Draft — crust from Aldi or Giant premade. Fresh mozzarella only — not shredded. Italian sausage can come from freezer stock — thaw if needed. Bake time TBC after first cook.",
    store: "Aldi / Giant",
  },
]
